apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-app-alerts
  labels:
    release: prometheus
spec:
  groups:
    - name: pod-status.rules
      rules:
        - alert: PodNotRunning
          expr: kube_pod_status_phase{phase!="Running"} > 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Pod not running"
            description: "One or more pods are not in Running state for more than 2 minutes."
